words = [
    "axios",
    "hmr",
    "inp",
    "linecap",
    "linejoin",
    "lyca",
    "mavenrick",
    "nums",
    "nvda",
    "prutech",
    "rtk",
    "terralogic",
    "zelevate",
    "zonejs",
]
